FROM pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime

WORKDIR /ScanRecepies

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONPATH=/ScanRecepies

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

CMD ["streamlit", "run", "client_boarding/run_onboarding.py", "--server.port=8501", "--server.address=0.0.0.0"]
