FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY cheflowlib/ cheflowlib/
COPY onboarding_dedupe/ .
CMD ["streamlit", "run", "run_onboarding.py", "--server.port=8501", "--server.address=0.0.0.0"]
