lemmatization:
    enabled: False
    language: "he"  # applicable if apply_lemmatization is True
use_word_embeddings: True
PCA: True # PCA for word embeddings - only if use_word_embeddings is True
PCA_COMPONENTS: 100  # PCA components for word embeddings - only if use_word_embeddings is True
DATA_LOADER:
#  - CSVDataLoader:
#      config:
#        filter_by:
#          "מוצר בסיס/ חומר גלם": "חומר גלם"
#        name_column: "שם הרכיב"
  - CSVListLoader:
      config:

PRE_CLASSIFIER:
  - EmbeddingClassifier:
      config:
        THRESHOLD: 0.85
        embedding_params:
          MODEL_NAME: "avichr/heBERT"
          PCA: True
          PCA_COMPONENTS: 50

REFINERS:
  - MinimalSimilarityRefiner:
      config:
        THRESHOLD: 0.7
        embedding_params:
          MODEL_NAME: "avichr/heBERT"
          PCA: False
