min_display_threshold: 0.75
certain_threshold: 0.999

CLASSIFIER_PARAMS:
    config:
      THRESHOLD: 0.85
      embedding_params:
        MODEL_NAME: "avichr/heBERT"
        PCA: True
        PCA_COMPONENTS: 50

MATCHER:
    threshold: 0.8

FINE_TUNNER:
    config:
      THRESHOLD: 0.7
      embedding_params:
        MODEL_NAME: "avichr/heBERT"
        PCA: False
