INVENTORY_DATA_LOADER:
  - CSVDataLoader:
      config:
        filter_by:
          "מוצר בסיס/ חומר גלם": "חומר גלם"
        name_column: "שם הרכיב"

CLIENT_DATA_LOADER:
  - CSVDataLoader:
      config:
        filter_by:
          "מוצר בסיס/ חומר גלם": "חומר גלם"
        name_column: "שם הרכיב"

MATCHER:
  - CosineSimilarityMatcher:
      threshold: 0.8
