# This is model configuration file - select model to use here
CURRENT_MODEL: DEEP_SEEK

MODEL:
  DEEP_SEEK:
    API_KEY_NAME: DEEP_SEEK_API_KEY
    BASE_URL: "https://api.deepseek.com"
    MODEL_NAME: "deepseek-chat"
    TOP_P: 0.97
    TEMPERATURE: 0.1
    LOGPROBS: True
    TOP_LOGPROBS: 5
  OPEN_AI:
    API_KEY_NAME: OPEN_AI_API_KEY
    BASE_URL:
    TOP_P: 0.97
    TEMPERATURE: 0.1
    LOGPROBS: True
    TOP_LOGPROBS: 5
