language: {{ language }}
logger: {{ logger }}
setup_config: {{ setup_config }}
units:  {{ units }}
DATABASE_INTERFACE:
  {{db_interface_class}}:
    db_config: {{ db_config }}
PROCESSING_PIPELINE:
  PRE_PROCESSORS:
    - TextCleaner:
        language: {{ language }}
    - TextSimplifier:
        max_tokens: 10000
        language: {{ language }}
        model_interface: {{ model_interface_class }}
  PROCESSOR:
    DefaultMainProcessor:
      model_interface: {{ model_interface_class }}
      prompts:
        DefaultPromptsContainer:
          force_ingredients: {{ force_ingredients | default(False) }}
          force_resources: {{ force_resources | default(False) }}
  POST_PROCESSORS:
    - GraphRefinement:
        model_interface: {{ model_interface_class }}
#    - PostProcessorsLoopContainer:
#        iterations: 1
#        language: {{ language }}
#        segment_config:
#          - RemoveFakeIngredients:
#          - RemoveFakeResources:
    - IngredientsSupplementaryFixer:
        refiner_prompts: SupplementaryRefinerPromptsContainer
        model_interface: {{ model_interface_class }}
        config:
          FIELDS:
            - quantity:
              - NotNull
              - TypeFloat
    - ResourcesSupplementaryFixer:
        refiner_prompts: SupplementaryRefinerPromptsContainer
        model_interface: {{ model_interface_class }}
        config:
          FIELDS:
            - temperature:
                - TypeFloat
            - usage_time:
                - TypeFloat
    - UnitsTransformer:
    - IngredientsNamesCorrector:
    - ResourcesNamesCorrector:
