# This file used to configure available resources and ingredients in the kitchen

ALLOWED_RESOURCES:
  - "קערה"
  - "מחבת"
  - "תנור"
  - "תבנית פיצה"
  - "מקרר"
  - "משתח עבודה"

ALLOWED_INGREDIENTS:
  "קמח": "g"
  "שמרים יבשים": "g"
  "סוכר": "g"
  "מלח": "g"
  "שמן זית": "ml"
  "מים פושרים": "ml"
  "עגבניות": "g"
  "שום": "g"
  "בזיליקום": "g"
  "רסק עגבניות": "g"
  "אורגנו יבש": "g"
  "גבינה קשה מגוררת": "g"
  "תוספות": "g"
  "בצק פיצה": ""
  "רוטב עגבניות": "g"

FINAL_NODE_NAME: "final_node"
